### ISSUE TITLE
Order of sessions

### ISSUE THREAD

**Issue by zouharvi** [GuusLake/User_Models#1]
As I understand it, each participant is going to go through the practice session and then three follow-up sessions with various intensity of billboard interruptions. My question is related to whether the order of these sessions is shuffled or kept constant. By shuffling I mean: `user0: practice-light-heavy-mixed`, `user1: practice-heavy-mixed-light`.

- If shuffled, this may create an additional influencing factor. For example, `user1` may be more prone to disregard the later sessions because they are not as interesting as the ones they saw at the beginning.
- If constant, you may discover some results that are particular only for this ordering. The later session may also be penalized because the participant is more tired and less interested in the experiment.

Overall, wouldn't a between-subject design be preferred for the session severity?

**Comment by GijsOW** [comment]
Firstly, a between-subject design would only make sense with very large sample of participants. With a small group, individual differences between participants would have too great an influence on the results. As for the session order: We will shuffle and randomize the order in which participants go through the phases. Indeed, what you suggested may happen, but because every participant has another order, and all orders will be equally represented, this effect will be accounted for. The same order for every participant would surely be biased, so that is not an option.

Thanks for your suggestion!
